name: recipe_finder
description: Recipe Finder App from Flutter Apprentice Book

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.3
  cached_network_image: 3.1.0
  flutter_slidable: 0.6.0
  flutter_svg: 0.22.0
  shared_preferences: 2.0.12
  json_annotation: 4.1.0
  http: 0.13.3
  chopper: 4.0.1 # development of networking code
  logging: 1.0.1 # To log network calls

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.1.1
  json_serializable: 4.1.4
  chopper_generator: 4.0.1
  
flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/