name: recipe_finder
description: Recipe Finder App from Flutter Apprentice Book

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

# https://pub.dev/
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.3
  cached_network_image: 3.1.0 # show images from the internet and keep them in the cache directory
  flutter_slidable: 0.6.0 # implementation of slidable list item with directional slide actions that can be dismissed
  flutter_svg: 0.22.0 # Draw SVG (and some Android VectorDrawable (XML)) files on a Flutter Widget
  shared_preferences: 2.0.12 # save the user preferences like search history
  json_annotation: 4.1.0 # Defines the annotations used by json_serializable to create code for JSON serialization and deserialization
  http: 0.13.3 # easy to consume HTTP resources
  chopper: 4.0.1 # development of networking code
  logging: 1.0.1 # To log network calls
  provider: 6.0.0 # for state management
  equatable: 2.0.3 # to check models for equality in maps and necessary for providers
  # sqflite: 2.0.0+4 # provides SQLite database access
  # path_provider: 2.0.2 # simplifies dealing with common file system locations
  # synchronized: 3.0.0 # helps implement lock mechanisms to prevent concurrent access, when needed
  sqlbrite: 2.1.0 # reactive wrapper around sqflite that receives changes happening in the database via streams
  moor_flutter: 4.0.0 # for dealing with database and repository

dependency_overrides:
  moor: 4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.1.1 # used to generate files
  json_serializable: 4.1.4 # to generate to/from JSON code for a class; to generate a Dart field
  chopper_generator: 4.0.1 # code generator for the Chopper package
  moor_generator: 4.4.1 # generator that turns your Table classes from moor into database code

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/